workspace:
  base: /drone
  path: /tmp

pipeline:
  build:
    image: smebberson/alpine-nginx
    commands:
      - env
      - echo "tag=build-${DRONE_BUILD_NUMBER}"
      - echo "tag=commit-${DRONE_COMMIT_SHA:0:8}"
      - echo "tag=version-${DRONE_COMMIT_TAG}"
    when:
      event: [push]