---
workspace:
  base: /node
  path: teston-chrome-extension

pipeline:
  test:
    image: eu.gcr.io/bold-upgrade-182112/teston-node
    commands:
      - npm install
      - npm run test
    when:
      branch: [ feature/*, hotfix/*, develop ]
      event:
        exclude: [ deployment ]

  build:
    image: eu.gcr.io/bold-upgrade-182112/teston-node
    commands:
      - npm install
      - npm run build

  publish_to_chrome_webstore:
    image: eu.gcr.io/bold-upgrade-182112/teston-node
    commands:
      - npm run make-package
      - npm run publish-extension
    when:
      environment: production
      branch: master
      event: deployment

  notify_prod:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: tech-announcements
    username: drone
    when:
      environment: production
      branch: master
      event: deployment
      status: [ success, failure ]
