workspace:
  base: /drone
  path: /tmp

pipeline:
  # build:
  #   image: golang:1.9
  #   commands:
  #     - env
  #   when:
  #     event: [push]

  publish:
    image: plugins/gcr
    # registry: eu.gcr.io
    # repo: bold-upgrade-182112/teston-pg
    secrets: [ gcr_json_key ]
    # tags:
    #   - '${DRONE_COMMIT:0:8}'
    commands:
      - env
      - ls
    # when:
    #   event: push
    #   branch: master

  # publish:
  #   image: eu.gcr.io/bold-upgrade-182112/teston-gcloud:latest
  #   secrets: [ gcr_json_key ]
  #   pull: true
  #   commands:
  #     - teston-drone-get-tag commit
  #     - teston-drone-get-tag build
  #     - teston-gcr-login
      # - teston-docker-build-image
    # when:
      # event: push
      # branch: master