---
workspace:
  base: /usr/local/teston/app
  path: drone-pg

pipeline:
  test:
    image: eu.gcr.io/bold-upgrade-182112/teston-node
    pull: true
    commands:
      - npm install
      - npm run test
    when:
      branch: [ feature/*, hotfix/*, develop ]
      event:
        exclude: [ deployment ]

  build:
    image: eu.gcr.io/bold-upgrade-182112/teston-node
    pull: true
    commands:
      - npm run build
    when:
      environment: production
      branch: master
      event: deployment

  publish_to_chrome_webstore:
    image: eu.gcr.io/bold-upgrade-182112/teston-node
    commands:
      - npm run publish
    secrets: [chrome_webstore_oauth_refresh_token, chrome_webstore_oauth_secret]
    when:
      environment: production
      branch: master
      event: deployment

  notify_prod:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: tech-announcements
    username: drone
    when:
      environment: production
      branch: master
      event: deployment
      status: [ success, failure ]
